export const constantData = {
  success: true,
  statusCode: 200,
  data: {
    count: 2,
    next: null,
    previous: null,
    results: [
      {
        employee_id: "2ea79c0a-f45a-43d1-bebe-9b6fe6c4ab9a",
        employee_first_name: "John",
        employee_last_name: "Nicholas",
        employee_job_title: "Registered Nurse",
        employee_type: "IN",
        scheduled_hours: 16.0,
        actual_hours: 0.0,
        overtime_hours: 0.0,
        confirmed_spend: 350.08,
        actual_spend: 0.0,
      },
      {
        employee_id: "fb90b158-5b0d-49bb-9a7e-ce6cd09c20af",
        employee_first_name: "George",
        employee_last_name: "Henrick",
        employee_job_title: "Registered Nurse",
        employee_type: "IN",
        scheduled_hours: 8.0,
        actual_hours: 0.0,
        overtime_hours: 0.0,
        confirmed_spend: 175.04,
        actual_spend: 0.0,
      },
    ],
  },
};
